version: '3.7'

services:
  app:
    build: ./app
    ports:
      - 3000:3000
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1
  db:
    build: ./db
    # environment:
    #   POSTGRES_PASSWORD: abcd
    ports:
      - 5432:5432
