version: '3.9'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod  # PROD file
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/init.prod.sql:/docker-entrypoint-initdb.d/init.prod.sql
    environment:
      POSTGRES_DB: aapi
      POSTGRES_HOST_AUTH_METHOD: trust
  