name: python-app-check

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  python-app-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install coverage flake8
    - name: Check flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests
      working-directory: ./app
      id: test-coverage
      run: |
        coverage run -m unittest discover test
        coverage report --omit "test*" | tail -c 5
        echo '::set-output name=rate::$(coverage report --omit "test*" | tail -c 5 | head -c -2 | xargs)'

    - name: Deploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          cd ~/comsw4156-project
          echo $PWD
          curl "https://img.shields.io/badge/coverage-${{ steps.random-color-generator.outputs.SELECTED_COLOR }}-00ff00" > badge.svg
        host: ${{ secrets.HOST }}
        username: ec2-user
        privateKey: ${{ secrets.PRIVATE_KEY}}
