# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo "Action triggered by a ${{ github.event_name }} event at ${GITHUB_REF#refs/heads/}"

      - name: Pull new code
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ~/comsw4156-project && git checkout ${GITHUB_REF#refs/heads/} && git pull --rebase
          host: ${{ secrets.HOST }}
          username: ec2-user
          privateKey: ${{ secrets.PRIVATE_KEY}}

      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ~/comsw4156-project && docker-compose -f docker-compose.prod.yml up -d --no-deps --build app
          host: ${{ secrets.HOST }}
          username: ec2-user
          privateKey: ${{ secrets.PRIVATE_KEY}}