name: Merge

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Print description
      run: echo "Action triggered by a ${{ github.event_name }} event at ${GITHUB_REF#refs/heads/}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install coverage flake8

    - name: Check flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      working-directory: ./app
      id: test-coverage
      run: |
        coverage run -m unittest discover test
        coverage report --omit "test*"
        coverage xml --omit "test*" -o test-coverage.xml

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
